# The Problem
<!-- 
Outlining the issue / weak point / problem to be solved by this proposal. This should be a compelling section that sets the reader up for the next section - the proposed solution!

It is important to cover:

 - [ ] What the problem is
 - [ ] Who it affects
 - [ ] Have there been previous attempts to resolve the problem
 - [ ] Why it should be tackled
-->

Analysis of spatio-temporal data is important for understanding, modeling and predicting the dynamics of our environment. With the rapid advancement and wide adoption of the [`sf`](https://cran.r-project.org/package=sf) package for spatial data and the [`stars`](https://cran.r-project.org/package=stars) package for regular spatial and spatio-temporal data, a new standard of spatial and spatio-temporal data handling in R has emerged. However, existing spatial statistics packages need to be adopted to fully benefit from these new developments. While coercion methods are in place and ensure a good deal of backwards compatibility, these transformations between data represenations are time and resource consuming and need explanation to novice users. Not having this hinders a straightforward deeper analysis of the data. Now that the new developemts around `sf` and `stars` have settled, many users rightly ask for compatibility between data representaions and modelling tools. 

The `stars` only handles _regular_ spatio-temporal data, where the time replications are identical for each spatial location. A lot of spatiotemporal data comes as irregular records (in tables with _lat_, _lon_, _time_, _value_ records), and in many cases _are_ not regular: examples include earthquakes, accidents, disease or death cases, lightning strikes, but also movement data which have further constraints. Statistical methods based on point pattern analysis or geostatistical interpolation are used to estimate, based on such irregular data, the incidence rates (densities) of events, or the values of e.g. air quality, again resulting in a regular spatiotemporal layout (e.g. a time sequence of raster or polygon maps).  To fill this gap, the package [`sftime`](https://github.com/r-spatial/sftime) has been initialised, but needs to be fully developed in order to close the gap for irregular spatio-temporal data. Downstream spatial statistics packages need to be adapted to support the spatiotemporal irregular data classes of `sftime` as input, and `stars` objects as output.
