# The proposal
<!--
This is where the proposal should be outlined. 
-->

This proposal does not explicitly address a topic or research question related to Covid-19, but the results will enable researchers in the R community to better organize and analyse their irregular spatiotemporal data related to the pandemic. The driving factor of the spread, the movement of people, but also the spatiotemporal distribution of current and future cases are per se irregular spatiotemporal data. Being able to easily visualise, aggregate and modell these data will help to better understand and control this and future pandemics. Filling the gap for irregular spatiotemporal data and providing direct interaction with analytical tools will ease the analysis for researchers. 

## Overview
<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->

We propose to develop the `sftime` package to a mature state so that the suite of modern spatial and spatiotemporal data representations in R includes irregular spatiotemporal data. After doing this, we will modify the geostatistical modelling package [`gstat`](https://cran.r-project.org/package=gstat) and the spatial copula modelling package [`spcopula`](https://github.com/bengraeler/spcopula) to support the new data representation classes of `sf`, `stars` and `sftime`. All packages will receive vignettes with worked out, full-fledge case studies, and results will be published on the `r-spatial.org` blog.

## Detail
<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->

### Package `sftime`

Package `sftime` is a new development extending the classes of package `sf` with spatiotemporal features. This package will be able to handle irregular spatiotemporal data as an S3 class. Implementations will include convenient construction methods, plotting capabilities and summaries of data objects. The development will be made available in the GitHub repository [r-spatial/sftime](https://github.com/r-spatial/sftime).  During the early phase of the project, we will actively request comments on and reviews of the implementation via the `R-sig-Geo` mailing list and from R developers in the domain. Once the package reaches a reasonably mature state, it will be submitted to CRAN to make it available to a larger community.
 
<!-- The minimal viable product will be a thorough implementation of a representation of irregular spatiotemporal data extending `sf` and compatible with `stars`. -->

### Package `gstat` 

The geostatistical modelling package `gstat` has a long history in the R community, and has been on CRAN since 2003. It provides methods to model spatial and spatiotemporal data based on various Kriging approaches. Currently, it can handle [`sp`](https:/cran.r-project.org/package=sp) and [`spacetime`](https:/cran.r-project.org/package=spacetime) objects. We will adapt the package to directly handle the full set of spatial and spatiotemporal data representations in packages `sf`, `stars` and `sftime`. Hence, no unnecessary back-and-forth conversions between data representations will be needed. This will shorten the analysis workflow and ease the application of methods in the `gstat` package in a modern data set-up.

### Package `spcopula`

The spatial copula modelling package `spcopula` implements a number of more recent developments of spatial statistics. While classical geostatistics is mainly rooted in a multivariate Gaussian assumption, copulas can take any multivariate distribution. This makes them particularly useful for skewed distributions or for modelling rare events. Currently, `spcopula` can only handle objects from `sp` or `spacetime`. We will adapt the methods of `spcopula` to also handle and benefit from the spatial and spatiotemporal data representations in packages `sf`, `stars` and `sftime` avoiding unnecessary coercions. Furthermore, `spcopula` will be upgraded to integrate with more recent developments in the packages [`copula`](https:cran.r-project.org/package=copula) and [`VineCopula`](https:cran.r-project.org/package=VineCopula), on which it depends.

### Development and Documentation

Throughout the development, we will provide example applications wrapped in vignettes in order to guide users on how to use the new functionality. These vignettes will also help interested developers of packages currently depending on `sp` and `spacetime` how their packages can be adapted to the new data representations. All developments throughout the project will be made available on-line and discussions are highly welcome. Final results will be published as blog posts on `r-spatial.org`.
