# Requirements
<!-- 
An idea of what is required to make the project actually happen
-->

## People
<!--
Who needs to be involved, what's the proposed structure, what will it take to get their involvement?
-->

Besides the applicants, we will discuss ideas and approaches with other developers in the domain. The mailing list `R-sig-Geo` is a good resource to discuss ideas and promote developments along with the tools offered via e.g. GitHub.

R-spatial developers we will actively involve for asking advice include: Roger Bivand, the `surveillance` authors Michael Höhle and Sebastian Meyer, and the `spatstat` author Ege Rubak.

## Processes
<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->

We will employ the same code of conduct as has been used for `sf`, found at [https://github.com/r-spatial/sf/blob/master/CONDUCT.md](https://github.com/r-spatial/sf/blob/master/CONDUCT.md); it is mostly a copy of the CoC developed by rOpenSci.
<!-- Ref? -->


## Tools and technologies
<!--
What is going to be needed to deliver this project? 

Will cloud computing be used - if yes are there are necessary components that will be deciding factors between providers?

Are there tools or tech that don't exist that will be produced to facilitate the project?
-->

All technical tools and technologies to deliver the outlined developments are already in place.

## Funding
<!-- 
[TO DO] THE GUIDANCE IS PRETTY UNCLEAR, ESP IN LIGHT OF GABOR'S PROPOSAL VS AWARD SIZE
-->

In order to pursue the developments, personal costs need to be subsidized. An estimated effort of 160 hours amounts to 10.000 USD.


<!--
## Summary

A summary of the requirements that contextualises the costs
-->
