# Project plan

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

The needed resources for a collaborative development of `sftime`, `gstat` and `spcopula` have already been initiated at GitHub. Intermediate and final reports will be published as blog posts on `r-spatial.org` and where appropriate be reflected in vignettes documenting the functionalities. The small size of the project team and already jointly developed packages will very much simplify the start-up phase. An initial design meeting will be scheduled for the very beginning of the project.


## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

The project is outlined for a 6 month period. The following milestones summarize the technical deliveries by month:

| milestone | `sftime` | `gstat` | `spcopula` |
|-----------|----------|---------|------------|
| M1 | data representation has been discussed and is defined  |  | upcoming changes in `copula` and `VineCopula` have been identified
| M2 | data can be stored; summary functions are present |  | recent developments have been included 
| M3 | objects can be constructed or coerced from `spacetime`, `sf` and simpler objects; initial plotting tools exist |  methods are adapted to `sf` and `stars` representations | methods are adapted to `sf` and `stars` representations
| M4 | plotting tools have been revised | methods are adapted to `sftime` representations | methods are adapted to `sftime` representations
| M5 | submitted to CRAN | submitted to CRAN | changes in `copula` and `VineCopula` haven been addressed
| M6 |   |   | submitted to CRAN 

In addition to the explicit schedule, the continuous development of related components will also serve as additional testing improving implementations, usability and documentation.

<!--
## Other aspects

Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->
